CREATE DATABASE accessapi;

ALTER DATABASE accessapi OWNER TO postgres;

\c accessapi;

CREATE SEQUENCE s_Genre START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE s_Utilisateur START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE s_Compte START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE s_Pin START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE s_Tentative START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE s_Token START 1 INCREMENT 1 NO CYCLE;