CREATE DATABASE accessapi;

ALTER DATABASE accessapi OWNER TO postgres;

\c accessapi;

CREATE SEQUENCE s_genre START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE s_utilisateur START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE s_compte START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE s_pin START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE s_tentative START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE s_token START 1 INCREMENT 1 NO CYCLE;
