create database crypto ;
\c crypto 

CREATE SEQUENCE s_utilisateur START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE s_crypto START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE s_portefeuille_detail START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE s_portefeuille START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE s_vente START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE s_achat START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE s_histocrypto START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE s_commission START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE s_fond START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE s_admin START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE s_fond_attente START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE s_historique_transaction START 1 INCREMENT 1 NO CYCLE;